### ISSUE TITLE
System.Exception: 'You have ServiceControl plugins installed in your endpoint......"

### ISSUE THREAD

**Issue by jbakholt** [Particular/ServiceControl.Plugin.Nsb6.Heartbeat#25]
When spinning up a MSMQ endpoint in a topshelf console app the app throws an exception: 

System.Exception: 'You have ServiceControl plugins installed in your endpoint, however, the Particular ServiceControl queue is not specified.
Please ensure that the Particular ServiceControl queue is specified either via code (config.HeartbeatPlugin(servicecontrolQueue)) or AppSettings (eg. <add key="ServiceControl/Queue" value="particular.servicecontrol@machine"/>).'

My app worked perfectly until I added the ServiceControl.Plugin.Nsb6.Heartbeat nuget package. The MSMQ endpoint will not be using ServiceControl.Plugin.Nsb6.Heartbeat but my plan is to spin up a second endpoint in the same host that uses both Heartbeat and SqlPersistence.

Repro:

1. New .NET 4.6.2 Console app
2. Set up topshelf
3. In the topshelf service class configure a MSMQ endpointconfiguration with InMemoryPersistence
4. Start the MSMQ endpoint by : var endpointInstance = Endpoint.Start(endpointConfiguration).ConfigureAwait(false).GetAwaiter().GetResult();
5. Everything should work just fine.
6. Now add the ServiceControl.Plugin.Nsb6.Heartbeat nuget package
7. Run the app again.
8. "Hopefully" it throws the aforementioned exception

**Comment by SzymonPobiega** [comment]
@jbakholt Sorry for the inconvenience. The current version of the plugins use assembly scanning and enable themselves whenever "found". In order to run two endpoints side-by-side in the same process, one with HB on and the other with HB off you need to explicitly disable the HB for the other endpoint using  `config.DisableFeature<Heartbeats>`. The new version of HB that will be realeased with NSB7 will required explicit enabling.

**Comment by jbakholt** [comment]
@SzymonPobiega Implemented the change and everything works fine now. Thanks a lot.
